  Accueil[m
  Add-City[m
* [32mAdministration[m
  Avatar[m
  Courses[m
  Courses-Build[m
  Dashboard-Teacher[m
  Delete-Account[m
  Deploy[m
  Develop[m
  Exercise[m
  ExtensionUuid[m
  Google-Analytic[m
  Heroku-Production[m
  Heroku-Staging[m
  HomePage[m
  Level[m
  Membership[m
  Membership-Not-User[m
  Messages[m
  New-Membership[m
  Post[m
  Prof-partners[m
  Referral[m
  Roles[m
  SEO-Friendly[m
  Style[m
  flavicon[m
  main[m
  platform[m
  richText[m
