# config/meta.yml

meta_title: "LNCLASS EDUCATION"
meta_description: "La plateforme de preparation du BAC en cote d'ivoire"
meta_image: "ln-icon.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@lnclass"
